language: node_js
node_js:
  - "10"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=b0768df2763f29fdbb69b1e9117d1003e8859c3946214e343107e0b7755c4cc1

before_script:
  - psql -c 'CREATE DATABASE ebanka;' -U postgres
  - npm install yarn@latest
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # - nyc --reporter=lcov
  #create and populate database
  #start server in background and continue with test
  # - nodemon server/index.js & //for production
  - npm run drop_testdb
  - npm run create_testdb
  - nyc npm run dev &
  - nyc npm test
  - nyc report --reporter=lcov

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js #&& rm -rf ./coverage
  - ./cc-test-reporter format-coverage coverage/coverage.json -t lcov -o coverage/lcov.info  # Format coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notification:
  email: false

# blocklist
branches:
  except:
  - api-two-db
# safelist
branches:
  only:
  - develop


  