language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

env:
  global:
    - CC_TEST_REPORTER_ID=b0768df2763f29fdbb69b1e9117d1003e8859c3946214e343107e0b7755c4cc1

before_script:
  - npm install yarn@latest
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # - nyc --reporter=lcov
  #start server in background and continue with test
  - nodemon server/index.js &
  - nyc npm test
  - nyc report --reporter=lcov

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.json #coverage/lcov.info  # Format coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notification:
  email: false

# blocklist
branches:
  except:
  - develop

# safelist
branches:
  only:
  - api-one

# deploy:
#   provider: heroku
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"
#   app: ebanka-api
#   on: api-one



  