language: node_js
node_js:
  - "10"

cache:
  directories:
    - "server/node_modules"

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  app: ebanka-api
  on: api-one

script:
  - npm server/test